### ISSUE TITLE
bug: Channel name

### ISSUE THREAD

**Issue by I2rys** [revoltchat/revite#712]
Channel name is not protected and It does not validate It's string unlike username.

![image](https://user-images.githubusercontent.com/87125939/175186170-424ee8a0-405f-4c83-bbf8-3460712f3dae.png)

**Comment by LedaThemis** [comment]
This is no longer an issue after 34bb2bbc135a3799e002d1e2377ba95b1f1c170f, as [RenderChannel](https://github.com/revoltchat/revite/blob/2b65e98cd3b9a67aa1fdfa92d62dbd2a336c0fc5/src/components/markdown/plugins/channels.tsx#L6-L15) renders channel name as text.

**Comment by I2rys** [comment]
> This is no longer an issue after [34bb2bb](https://github.com/revoltchat/revite/commit/34bb2bbc135a3799e002d1e2377ba95b1f1c170f), as [RenderChannel](https://github.com/revoltchat/revite/blob/2b65e98cd3b9a67aa1fdfa92d62dbd2a336c0fc5/src/components/markdown/plugins/channels.tsx#L6-L15) renders channel name as text.

Still an issue.

**Comment by LedaThemis** [comment]
> It's still an issue.

hm, can't reproduce it.
setting channel name to "]#[" renders the following:
![channel name displayed as `]#[` with link working](https://user-images.githubusercontent.com/38331868/178142649-1752cdf5-88bc-4fa0-a245-3d1451408821.png)
commit hash: [2b65e98](https://github.com/revoltchat/revite/commit/2b65e98cd3b9a67aa1fdfa92d62dbd2a336c0fc5)

**Comment by insertish** [comment]
Was fixed as above.

**Comment by I2rys** [comment]
> > It's still an issue.
> 
> hm, can't reproduce it. setting channel name to "]#[" renders the following: ![channel name displayed as ]#[ with link working](https://user-images.githubusercontent.com/38331868/178142649-1752cdf5-88bc-4fa0-a245-3d1451408821.png) commit hash: [2b65e98](https://github.com/revoltchat/revite/commit/2b65e98cd3b9a67aa1fdfa92d62dbd2a336c0fc5)

Well... It's not fixed for me. I even created a new server to test.
![image](https://user-images.githubusercontent.com/87125939/178168038-0071d870-b547-4ff2-bf32-9252747da4a3.png)

**Comment by LedaThemis** [comment]
> Well... It's not fixed for me. I even created a new server to test.

What is your commit hash? (you can find that at the bottom of settings)

**Comment by I2rys** [comment]
> > Well... It's not fixed for me. I even created a new server to test.
> 
> What is your commit hash? (you can find that at the bottom of settings)

https://github.com/revoltchat/revite/commit/b53d3bce133d52b114739dd705727ef5a69c36ee

**Comment by Rexogamer** [comment]
Reload the app and click the green update button in the top left corner then check again - you're using an outdated version

**Comment by I2rys** [comment]
> Reload the app and click the green update button in the top left corner then check again - you're using an outdated version

I'm using the web version so does the web version have a "green update button"?

**Comment by LedaThemis** [comment]
> https://github.com/revoltchat/revite/commit/b53d3bce133d52b114739dd705727ef5a69c36ee

> you're using an outdated version

This is [production](https://app.revolt.chat), in which the [commit that fixed the bug](https://github.com/revoltchat/revite/commit/34bb2bbc135a3799e002d1e2377ba95b1f1c170f) isn't live yet, but it's live in [nightly](https://nightly.revolt.chat).

**Comment by I2rys** [comment]
> > [b53d3bc](https://github.com/revoltchat/revite/commit/b53d3bce133d52b114739dd705727ef5a69c36ee)
> 
> > you're using an outdated version
> 
> This is [production](https://app.revolt.chat), in which the [commit that fixed the bug](https://github.com/revoltchat/revite/commit/34bb2bbc135a3799e002d1e2377ba95b1f1c170f) isn't live yet, but it's live in [nightly](https://nightly.revolt.chat).

Oh I see, so It's fixed then. 🍻
